// ══════════════════════════════════════════════════════════════════
// DESIGN TOKENS
// ══════════════════════════════════════════════════════════════════
export const C = {
  bg: "var(--c-bg)",
  bgAlt: "var(--c-bgalt)",
  surface: "var(--c-surface)",
  surfaceWarm: "var(--c-surfacewarm)",
  border: "var(--c-border)",
  borderLight: "var(--c-borderlight)",
  text: "var(--c-text)",
  sub: "var(--c-sub)",
  muted: "var(--c-muted)",
  amber: "var(--c-amber)",
  amberMid: "var(--c-ambermid)",
  amberLight: "var(--c-amberlight)",
  amberBorder: "var(--c-amberborder)",
  sidebar: "var(--c-sidebar)",
  sidebarAlt: "var(--c-sidebaralt)",
  sidebarBorder: "var(--c-sidebarborder)",
  sidebarText: "var(--c-sidebartext)",
  sidebarMuted: "var(--c-sidebarmuted)",
  green: "var(--c-green)",
  greenLight: "var(--c-greenlight)",
  greenBorder: "var(--c-greenborder)",
  blue: "var(--c-blue)",
  blueLight: "var(--c-bluelight)",
  blueBorder: "var(--c-blueborder)",
  red: "var(--c-red)",
  redLight: "var(--c-redlight)",
  redBorder: "var(--c-redborder)",
  orange: "var(--c-orange)",
  orangeLight: "var(--c-orangelight)",
  orangeBorder: "var(--c-orangeborder)",
  purple: "var(--c-purple)",
  purpleLight: "var(--c-purplelight)",
  purpleBorder: "var(--c-purpleborder)",
  shadow: "var(--c-shadow)",
  shadowMd: "var(--c-shadowmd)",
  shadowLg: "var(--c-shadowlg)",
  shadowHover: "var(--c-shadowhover)",
  navy: "#0d1117",
};

export const RISK: Record<string, { text: string; bg: string; border: string; dot: string }> = {
  "MUY ALTO": { text: "#991b1b", bg: "#fef2f2", border: "#fca5a5", dot: "#ef4444" },
  "ALTO": { text: "#9a3412", bg: "#fff7ed", border: "#fdba74", dot: "#f97316" },
  "SIGNIFICATIVO": { text: "#854d0e", bg: "#fefce8", border: "#fde047", dot: "#eab308" },
  "BAJO": { text: "#166534", bg: "#f0fdf4", border: "#86efac", dot: "#22c55e" },
  "DESPRECIABLE": { text: "#374151", bg: "#f9fafb", border: "#d1d5db", dot: "#9ca3af" },
};

export const NTC: Record<string, { bg: string; text: string; border: string }> = {
  A: { bg: "#ede9fe", text: "#5b21b6", border: "#c4b5fd" },
  B: { bg: "#dbeafe", text: "#1d4ed8", border: "#93c5fd" },
  C: { bg: "#d1fae5", text: "#065f46", border: "#6ee7b7" },
  Local: { bg: "#fef3c7", text: "#92400e", border: "#fcd34d" },
};

export const STATUS_CFG: Record<string, { bg: string; border: string; text: string; label: string }> = {
  "CUMPLE": { bg: C.greenLight, border: C.greenBorder, text: C.green, label: "CUMPLE" },
  "NO CUMPLE": { bg: C.redLight, border: C.redBorder, text: C.red, label: "NO CUMPLE" },
  "PARCIAL": { bg: C.orangeLight, border: C.orangeBorder, text: C.orange, label: "PARCIAL" },
  "N/A": { bg: "#f8fafc", border: "#cbd5e1", text: "#475569", label: "N/A" },
};

export const TYPE_META = {
  DISEÑO: { label: "Proyecto de Diseño", icon: "📐", color: "#2563eb", bg: "#eff6ff", border: "#93c5fd" },
  MAQUINA_INSTALADA: { label: "Máquina Instalada", icon: "⚙️", color: "#16a34a", bg: "#f0fdf4", border: "#86efac" },
};

export const PHASE_META = [
  { num: 1, label: "Determinación de Límites y Alcance", ref: "ISO 12100:2010 §5.3", color: "#7c3aed", bg: "#ede9fe", border: "#c4b5fd", icon: "📐" },
  { num: 2, label: "Diseño Inherentemente Seguro", ref: "ISO 12100:2010 §6.2", color: "#0369a1", bg: "#e0f2fe", border: "#7dd3fc", icon: "🛡" },
  { num: 3, label: "Funciones de Seguridad y PLr", ref: "ISO 13849-1 / IEC 62061", color: "#0f766e", bg: "#ccfbf1", border: "#5eead4", icon: "⚡" },
  { num: 4, label: "Resguardos y Dispositivos de Protección", ref: "ISO 12100 §6.3 / ISO 14119 / ISO 13855", color: "#b45309", bg: "#fef3c7", border: "#fde68a", icon: "🔒" },
  { num: 5, label: "Validación e Información para el Uso", ref: "ISO 12100:2010 §6.4", color: "#166534", bg: "#f0fdf4", border: "#86efac", icon: "✅" },
  { num: 6, label: "Integración de Sistemas Robotizados", ref: "ISO 10218-1/2 / ISO/TS 15066", color: "#9f1239", bg: "#fff1f2", border: "#fda4af", icon: "🤖", optional: true },
  { num: 7, label: "Legislación Argentina y NR-12", ref: "Ley 19587 / Decreto 351/79 / NR-12", color: "#92400e", bg: "#fef3c7", border: "#fcd34d", icon: "⚖️" },
];

export const RFQ = [
  // ═══════════════════════════════════════════════════════════════
  // FASE 1 — Determinación de Límites (24 ítems)
  // ═══════════════════════════════════════════════════════════════
  {id:"r01",code:"1.1",num:1,phase:1,section:"A. Límites de uso y de los usuarios",optional:false,resp:"Fabricante / Integrador",
   q:"¿Está documentado el uso previsto de la máquina, la descripción de sus funciones y el análisis de las secuencias de proceso?",
   e:"El documento de uso previsto es la base de todo análisis de peligros posterior. Debe incluir la descripción funcional completa, secuencias de proceso, modos de operación previstos y cualquier restricción de uso conocida.",
  },
  {id:"r02",code:"1.2",num:2,phase:1,section:"A. Límites de uso y de los usuarios",optional:false,resp:"Fabricante / Integrador",
   q:"¿Están documentadas las malas prácticas y el uso indebido razonablemente previsible del sistema?",
   e:"El uso indebido razonablemente previsible es aquel derivado del comportamiento humano instintivo o predecible, aunque no sea el uso correcto.",
  },
  {id:"r03",code:"1.3",num:3,phase:1,section:"A. Límites de uso y de los usuarios",optional:false,resp:"Fabricante / Integrador",
   q:"¿Están definidos de forma explícita todos los modos de uso o funcionamiento (automático, aprendizaje, reglaje, intervención manual)?",
   e:"Cada modo de funcionamiento puede tener un perfil de riesgo diferente.",
  },
  {id:"r04",code:"1.4",num:4,phase:1,section:"A. Límites de uso y de los usuarios",optional:false,resp:"Fabricante / Usuario final",
   q:"¿Están identificados todos los usuarios previstos (operarios, mantenimiento, visitantes) y definidas las habilidades y nivel de capacitación necesarios para cada perfil?",
   e:"La norma requiere que el diseño contemple al usuario menos experimentado.",
  },
  {id:"r05",code:"1.5",num:5,phase:1,section:"A. Límites de uso y de los usuarios",optional:false,resp:"Fabricante",
   q:"¿Se consideraron las características físicas y biomecánicas de los usuarios (sexo, edad, destreza, fuerza limitada, aptitudes físicas)?",
   e:"Los percentiles antropométricos de referencia deben estar documentados.",
  },
  {id:"r06",code:"1.6",num:6,phase:1,section:"B. Límites espaciales y de interfaz",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se determinó el alcance máximo y necesario del movimiento del sistema, la zona de peligro y los espacios requeridos para instalación, operación y mantenimiento?",
   e:"Los límites espaciales definen el perímetro de riesgo y son la base para el cálculo de distancias.",
  },
  {id:"r07",code:"1.7",num:7,phase:1,section:"B. Límites espaciales y de interfaz",optional:false,resp:"Fabricante / Integrador",
   q:"¿Están documentadas claramente las interfaces operario-máquina, herramientas conectadas y conexiones de alimentación de energía?",
   e:"Fuentes potenciales de energía peligrosa residual deben contemplarse en LOTO.",
  },
  {id:"r08",code:"1.8",num:8,phase:1,section:"B. Límites espaciales y de interfaz",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se definieron las exigencias dimensionales de acceso y los espacios libres mínimos para que el personal interactúe de forma segura?",
   e:"ISO 13857 define las distancias mínimas para evitar aplastamiento.",
  },
  {id:"r09",code:"1.9",num:9,phase:1,section:"B. Límites espaciales y de interfaz",optional:false,resp:"Integrador / Usuario final",
   q:"¿Se establecieron los requisitos técnicos de cimentación específicos para soportar las dinámicas del sistema?",
   e:"Una cimentación insuficiente puede desalinear sensores de seguridad.",
  },
  {id:"r10",code:"1.10",num:10,phase:1,section:"C. Límites temporales (ciclo de vida)",optional:false,resp:"Fabricante",
   q:"¿Están identificadas todas las fases del ciclo que deben cubrirse en el diseño?",
   e:"Transporte, instalación, puesta en servicio, operación, limpieza.",
  },
  {id:"r11",code:"1.11",num:11,phase:1,section:"C. Límites temporales (ciclo de vida)",optional:false,resp:"Fabricante",
   q:"¿Está definida la vida útil prevista de la maquinaria y de sus componentes críticos sometidos a desgaste?",
   e:"Afecta directamente el cálculo de MTTFd y el PL alcanzable.",
  },
  {id:"r12",code:"1.12",num:12,phase:1,section:"C. Límites temporales (ciclo de vida)",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se documentaron los intervalos y frecuencias de revisión recomendadas para el mantenimiento preventivo?",
   e:"Intervalos deben ser coherentes con B10d de los componentes.",
  },
  {id:"r13",code:"1.13",num:13,phase:1,section:"D. Otros límites (entorno, energía, materiales)",optional:false,resp:"Fabricante / Integrador",
   q:"¿Están identificadas todas las fuentes de energía (eléctrica, neumática, hidráulica, cinética)?",
   e:"Energía acumulada (presión residual, resortes, gravedad).",
  },
  {id:"r14",code:"1.14",num:14,phase:1,section:"D. Otros límites (entorno, energía, materiales)",optional:false,resp:"Fabricante / Integrador",
   q:"¿Están definidos los límites del entorno de trabajo (temperatura, presión, contaminación, humedad)?",
   e:"Afecta grados IP y vida útil de semiconductores.",
  },
  {id:"r15",code:"1.15",num:15,phase:1,section:"D. Otros límites (entorno, energía, materiales)",optional:false,resp:"Integrador / Usuario final",
   q:"¿Se han documentado las propiedades físicas y químicas de los materiales a procesar?",
   e:"Humos, toxicidad, inflamabilidad (inyectoras).",
  },
  {id:"r16",code:"1.16",num:16,phase:1,section:"D. Otros límites (entorno, energía, materiales)",optional:false,resp:"Fabricante / Usuario final",
   q:"¿Se estableció el nivel de conservación y limpieza requerido para la seguridad?",
   e:"Contaminación en sensores puede anular funciones de seguridad.",
  },
  {id:"r17",code:"1.17",num:17,phase:1,section:"E. Identificación sistemática de peligros",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se han identificado todas las interacciones humanas: reglaje, aprendizaje, limpieza, mantenimiento?",
   e:"Alimenta directamente los parámetros F, S y P del PLr.",
  },
  {id:"r18",code:"1.18",num:18,phase:1,section:"E. Identificación sistemática de peligros",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se evaluaron los peligros durante fallos del control, atascos y puestas en marcha imprevistas?",
   e:"Estados anómalos son la mayor fuente de accidentes graves.",
  },
  {id:"r19",code:"1.19",num:19,phase:1,section:"E. Identificación sistemática de peligros",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se documentaron sistemáticamente las fuentes de peligro: mecánicos, eléctricos, térmicos?",
   e:"ISO 12100 Anexo B sirve de referencia sistemática.",
  },
  {id:"r20",code:"1.20",num:20,phase:1,section:"E. Identificación sistemática de peligros",optional:true,resp:"Integrador",
   q:"(Robots) ¿Se identificaron situaciones de intervención directa dentro del espacio de seguridad?",
   e:"Modos de aprendizaje con dispositivos de validación de 3 posiciones.",
  },
  {id:"r21",code:"1.21",num:21,phase:1,section:"E. Identificación sistemática de peligros",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se determinó la gravedad máxima previsible para cada peligro (S1 vs S2)?",
   e:"S2 implica lesión irreversible, amputación o muerte.",
  },
  {id:"r22",code:"1.22",num:22,phase:1,section:"E. Identificación sistemática de peligros",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se analizó la frecuencia y duración de la exposición (F1 vs F2)?",
   e:"F2: >1 vez por hora o >15 minutos de duración.",
  },
  {id:"r23",code:"1.23",num:23,phase:1,section:"E. Identificación sistemática de peligros",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se consideró la posibilidad de evitar el daño (P1 vs P2)?",
   e:"P2: Trayectoria no predecible o alta velocidad.",
  },
  {id:"r24",code:"1.24",num:24,phase:1,section:"E. Identificación sistemática de peligros",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se determinó formalmente si el riesgo es aceptable o exige reducción?",
   e:"Evaluación iterativa mandataria según ISO 12100 §6.",
  },

  // ═══════════════════════════════════════════════════════════════
  // FASE 2 — Diseño Inherentemente Seguro (16 ítems)
  // ═══════════════════════════════════════════════════════════════
  {id:"r25",code:"2.1",num:25,phase:2,section:"A. Factores geométricos, físicos y visibilidad",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se han dimensionado correctamente las distancias mínimas para evitar aplastamientos?",
   e:"ISO 13857: 25mm dedos, 80mm manos, 120mm brazos.",
  },
  {id:"r26",code:"2.2",num:26,phase:2,section:"A. Factores geométricos, físicos y visibilidad",optional:false,resp:"Fabricante / Integrador",
   q:"¿El diseño maximiza la visibilidad directa de las zonas de peligro?",
   e:"Confirmar ausencia de personas antes del arranque.",
  },
  {id:"r27",code:"2.3",num:27,phase:2,section:"A. Factores geométricos, físicos y visibilidad",optional:false,resp:"OEM / Integrador",
   q:"¿Se han limitado masas, velocidades y presiones para reducir energía cinética?",
   e:"Muy relevante en robots colaborativos y modo manual (250mm/s).",
  },
  {id:"r28",code:"2.4",num:28,phase:2,section:"A. Factores geométricos, físicos y visibilidad",optional:false,resp:"OEM",
   q:"¿Se aseguró la estabilidad estática y dinámica considerando vibraciones?",
   e:"Un robot a máxima aceleración ejerce momentos considerables.",
  },
  {id:"r29",code:"2.5",num:29,phase:2,section:"B. Propiedades de los materiales y tecnología",optional:false,resp:"OEM",
   q:"¿Se seleccionaron materiales adecuados frente a fatiga, desgaste y corrosión?",
   e:"Ventanas de resguardos deben resistir proyecciones.",
  },
  {id:"r30",code:"2.6",num:30,phase:2,section:"B. Propiedades de los materiales y tecnología",optional:false,resp:"OEM / Integrador",
   q:"¿Se aplicó el diseño de acción mecánica positiva en componentes críticos?",
   e:"No depender de resortes que pueden fallar.",
  },
  {id:"r31",code:"2.7",num:31,phase:2,section:"B. Propiedades de los materiales y tecnología",optional:false,resp:"OEM / Integrador",
   q:"¿Se redujeron inherentemente ruido, vibraciones y sustancias peligrosas?",
   e:"Preferencia por reducción en la fuente sobre EPP.",
  },
  {id:"r32",code:"2.8",num:32,phase:2,section:"C. Ergonomía e interacción humana (HMI)",optional:false,resp:"OEM / Integrador",
   q:"¿Se evitaron posturas forzadas y esfuerzos excesivos?",
   e:"Evaluar con metodologías NIOSH / RULA.",
  },
  {id:"r33",code:"2.9",num:33,phase:2,section:"C. Ergonomía e interacción humana (HMI)",optional:false,resp:"OEM / Integrador",
   q:"¿Se diseñaron los mandos considerando la anatomía humana?",
   e:"Pulsadores de emergencia accesibles sin obstáculos.",
  },
  {id:"r34",code:"2.10",num:34,phase:2,section:"C. Ergonomía e interacción humana (HMI)",optional:false,resp:"OEM / Integrador",
   q:"¿La máquina dispone de iluminación localizada, libre de sombras?",
   e:"Niveles mínimos s/ Dec 351/79 Anexo IV.",
  },
  {id:"r35",code:"2.11",num:35,phase:2,section:"D. Intervención, automatización y mantenibilidad",optional:false,resp:"OEM / Integrador",
   q:"¿Se automatizaron tareas peligrosas de alimentación o extracción?",
   e:"La mejor forma de reducir exposición es sacando al operador de la zona.",
  },
  {id:"r36",code:"2.12",num:36,phase:2,section:"D. Intervención, automatización y mantenibilidad",optional:false,resp:"OEM / Integrador",
   q:"¿Los puntos de mantenimiento se ubicaron fuera de las zonas peligrosas?",
   e:"Engrase o ajustes desde el exterior sin abrir resguardos.",
  },
  {id:"r37",code:"2.13",num:37,phase:2,section:"D. Intervención, automatización y mantenibilidad",optional:false,resp:"OEM / Integrador",
   q:"¿Se diseñó para que el mantenimiento rutinario se realice a nivel del suelo?",
   e:"Evitar trabajos en altura siempre que sea posible.",
  },
  {id:"r38",code:"2.14",num:38,phase:2,section:"E. Sistemas de mando relativos a la seguridad (SRP/CS)",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se utilizaron componentes de eficacia probada (well-tried)?",
   e:"Basarse en historial de uso satisfactorio (ISO 13849-2).",
  },
  {id:"r39",code:"2.15",num:39,phase:2,section:"E. Sistemas de mando relativos a la seguridad (SRP/CS)",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se diseñaron los sistemas bajo el principio fail-safe?",
   e:"Un fallo debe conducir al estado de mayor seguridad.",
  },
  {id:"r40",code:"2.16",num:40,phase:2,section:"E. Sistemas de mando relativos a la seguridad (SRP/CS)",optional:false,resp:"Fabricante / Integrador",
   q:"¿Se integraron medios para prevenir arranques intempestivos?",
   e:"Requiere acción deliberada (rearme) tras stop de emergencia.",
  },

  // ═══════════════════════════════════════════════════════════════
  // FASE 3 — Funciones de Seguridad y PLr (14 ítems)
  // ═══════════════════════════════════════════════════════════════
  {id:"r41",code:"3.1",num:41,phase:3,section:"A. Identificación y especificación de funciones",optional:false,resp:"Integrador",
   q:"¿Están identificadas todas las funciones de seguridad (SF)?",
   e:"Stop emergencia, prevención arranque, velocidad limitada.",
  },
  {id:"r42",code:"3.2",num:42,phase:3,section:"A. Identificación y especificación de funciones",optional:false,resp:"Integrador",
   q:"¿Se documentó la matriz de modos vs funciones de seguridad?",
   e:"SF activas por modo.",
  },
  {id:"r43",code:"3.3",num:43,phase:3,section:"A. Identificación y especificación de funciones",optional:false,resp:"Integrador",
   q:"¿Están definidas las categorías de parada (IEC 60204-1)?",
   e:"Cat 0, 1 o 2.",
  },
  {id:"r44",code:"3.4",num:44,phase:3,section:"A. Identificación y especificación de funciones",optional:false,resp:"Integrador",
   q:"¿Se especificaron tiempos de respuesta y distancias de parada?",
   e:"Base para el cálculo de distancias de seguridad (ISO 13855).",
  },
  {id:"r45",code:"3.5",num:45,phase:3,section:"B. Determinación del PLr",optional:false,resp:"Integrador",
   q:"¿Se determinó el PLr (a-e) para cada función?",
   e:"Usando gráfico de riesgo ISO 13849-1 Anexo A.",
  },
  {id:"r46",code:"3.6",num:46,phase:3,section:"B. Determinación del PLr",optional:true,resp:"Integrador",
   q:"(Robots) ¿Se alcanza mínimo PL d con arquitectura Categoría 3?",
   e:"Requisito mandatorio de ISO 10218-1.",
  },
  {id:"r47",code:"3.7",num:47,phase:3,section:"C. Arquitectura y cuantificación de hardware",optional:false,resp:"Integrador",
   q:"¿Se definió la arquitectura / categoría (B, 1, 2, 3, 4)?",
   e:"Determina la estructura lógica del sistema.",
  },
  {id:"r48",code:"3.8",num:48,phase:3,section:"C. Arquitectura y cuantificación de hardware",optional:false,resp:"Integrador",
   q:"¿Se calculó el MTTFd (Mean Time to Dangerous Failure)?",
   e:"Fiabilidad de los componentes (máx 100 años).",
  },
  {id:"r49",code:"3.9",num:49,phase:3,section:"C. Arquitectura y cuantificación de hardware",optional:false,resp:"Integrador",
   q:"¿Se evaluó la Cobertura de Diagnóstico (DC)?",
   e:"Detección automática de fallos peligrosos.",
  },
  {id:"r50",code:"3.10",num:50,phase:3,section:"C. Arquitectura y cuantificación de hardware",optional:false,resp:"Integrador",
   q:"¿Se evaluaron las medidas contra fallos de causa común (CCF)?",
   e:"Mínimo 65 puntos según Anexo F.",
  },
  {id:"r51",code:"3.11",num:51,phase:3,section:"D. Soporte lógico relativo a la seguridad",optional:false,resp:"Integrador",
   q:"¿El Safety PLC tiene certificación para el SIL/PL requerido?",
   e:"Un PLC estándar no puede realizar funciones de seguridad.",
  },
  {id:"r52",code:"3.12",num:52,phase:3,section:"D. Soporte lógico relativo a la seguridad",optional:false,resp:"Integrador",
   q:"¿Se aplicaron medidas para evitar fallos sistemáticos en software?",
   e:"Bloques certificados, programación modular, protección password.",
  },
  {id:"r53",code:"3.13",num:53,phase:3,section:"E. Verificación global del subsistema",optional:false,resp:"Integrador",
   q:"¿Se verificó formalmente que PL obtenido ≥ PLr?",
   e:"Uso de herramienta SISTEMA o equivalente.",
  },
  {id:"r54",code:"3.14",num:54,phase:3,section:"E. Verificación global del subsistema",optional:false,resp:"Integrador",
   q:"¿Está documentada la justificación de cualquier exclusión de defecto?",
   e:"Basada en ISO 13849-2.",
  },

  // ═══════════════════════════════════════════════════════════════
  // FASE 4 — Resguardos y Dispositivos de Protección (10 ítems)
  // ═══════════════════════════════════════════════════════════════
  {id:"r55",code:"4.1",num:55,phase:4,section:"A. Resguardos físicos",optional:false,resp:"Integrador",
   q:"¿Respetan los resguardos las distancias de seguridad (ISO 13857)?",
   e:"Altura mínima 1400mm para células robotizadas.",
  },
  {id:"r56",code:"4.2",num:56,phase:4,section:"A. Resguardos físicos",optional:false,resp:"Integrador",
   q:"¿Requieren los resguardos fijos herramienta para desmontaje?",
   e:"Tornillería imperdible / cautiva según ISO 14120.",
  },
  {id:"r57",code:"4.3",num:57,phase:4,section:"A. Resguardos físicos",optional:false,resp:"Integrador",
   q:"¿Tienen rigidez para resistir esfuerzos y proyecciones?",
   e:"Especialmente piezas calientes en inyectoras.",
  },
  {id:"r58",code:"4.4",num:58,phase:4,section:"A. Resguardos físicos",optional:false,resp:"Integrador",
   q:"¿Se especificó enclavamiento con bloqueo si Tiempo Parada > Tiempo Acceso?",
   e:"Calculado con fórmula ISO 13855.",
  },
  {id:"r59",code:"4.5",num:59,phase:4,section:"A. Resguardos físicos",optional:false,resp:"Integrador",
   q:"¿Se aplicaron medidas contra la neutralización (bypass)?",
   e:"Uso de RFID o actuadores codificados (ISO 14119).",
  },
  {id:"r60",code:"4.6",num:60,phase:4,section:"B. Dispositivos electrosensibles (ESPE)",optional:false,resp:"Integrador",
   q:"¿Se calculó la distancia mínima de cortinas de luz?",
   e:"S = K × (t1 + t2).",
  },
  {id:"r61",code:"4.7",num:61,phase:4,section:"B. Dispositivos electrosensibles (ESPE)",optional:false,resp:"Integrador",
   q:"¿Es imposible alcanzar el peligro por encima o permanecer oculto?",
   e:"Scanners internos para evitar trampas en zonas muertas.",
  },
  {id:"r62",code:"4.8",num:62,phase:4,section:"C. Dispositivos de parada, rearme y advertencia",optional:false,resp:"Integrador / Usuario",
   q:"¿Pulsadores de emergencia visibles y accesibles?",
   e:"Rojos sobre fondo amarillo, retención mecánica.",
  },
  {id:"r63",code:"4.9",num:63,phase:4,section:"C. Dispositivos de parada, rearme y advertencia",optional:false,resp:"Integrador",
   q:"¿Pulsador de rearme ubicado con visión total de la zona?",
   e:"Fuera del espacio de seguridad.",
  },
  {id:"r64",code:"4.10",num:64,phase:4,section:"C. Dispositivos de parada, rearme y advertencia",optional:false,resp:"Integrador",
   q:"¿Medidas suplementarias si existen ángulos muertos visuales?",
   e:"Sirenas y luces previas al arranque (3-5 seg).",
  },

  // ═══════════════════════════════════════════════════════════════
  // FASE 5 — Validación e Información para el Uso (6 ítems)
  // ═══════════════════════════════════════════════════════════════
  {id:"r65",code:"5.1",num:65,phase:5,section:"A. Validación del sistema (V&V)",optional:false,resp:"Integrador",
   q:"¿Existe un plan e informe final de validación?",
   e:"Ensayos de inyección de fallos según ISO 13849-2.",
  },
  {id:"r66",code:"5.2",num:66,phase:5,section:"B. Información para la utilización",optional:false,resp:"OEM / Integrador",
   q:"¿Manual incluye uso previsto y riesgos residuales?",
   e:"EPP requerido y formación necesaria.",
  },
  {id:"r67",code:"5.3",num:67,phase:5,section:"B. Información para la utilización",optional:false,resp:"Integrador",
   q:"¿Esquemas finales con codificación de componentes as-built?",
   e:"Eléctricos, neumáticos, hidráulicos.",
  },
  {id:"r68",code:"5.4",num:68,phase:5,section:"B. Información para la utilización",optional:false,resp:"Integrador / Usuario",
   q:"¿Documentadas prácticas de LOTO y emergencias?",
   e:"Procedimientos específicos por tarea.",
  },
  {id:"r69",code:"5.5",num:69,phase:5,section:"C. Señalización, marcas y advertencias",optional:false,resp:"OEM / Integrador",
   q:"¿Placa de identificación visible e indeleble?",
   e:"Razón social, serie, año, límites dinámicos.",
  },
  {id:"r70",code:"5.6",num:70,phase:5,section:"C. Señalización, marcas y advertencias",optional:false,resp:"Integrador / Usuario",
   q:"¿Pictogramas (ISO 7010) y alarmas planificadas?",
   e:"Evitar saturación sensorial y falsas alarmas.",
  },

  // ═══════════════════════════════════════════════════════════════
  // FASE 6 — Sistemas Robotizados (7 ítems)
  // ═══════════════════════════════════════════════════════════════
  {id:"r71",code:"6.1",num:71,phase:6,section:"A. Limitación del espacio y movimientos",optional:true,resp:"Integrador",
   q:"¿Espacio restringido definido por topes o software seguro?",
   e:"SafeMove, DCS o similar.",
  },
  {id:"r72",code:"6.2",num:72,phase:6,section:"B. Operación manual y aprendizaje",optional:true,resp:"Integrador",
   q:"¿Velocidad limitada a 250mm/s y dispositivo de 3 posiciones?",
   e:"ISO 10218-1.",
  },
  {id:"r73",code:"6.3",num:73,phase:6,section:"B. Operación manual y aprendizaje",optional:true,resp:"Integrador",
   q:"¿Funciones ISO/TS 15066 para cobots?",
   e:"Limitación de potencia y fuerza.",
  },
  {id:"r74",code:"6.4",num:74,phase:6,section:"C. Interfaz con el sistema (IMS)",optional:true,resp:"Integrador",
   q:"¿Parada de emergencia interconectada entre máquinas?",
   e:"Span of control: detener todos los peligros solapados.",
  },
  {id:"r75",code:"6.5",num:75,phase:6,section:"C. Interfaz con el sistema (IMS)",optional:true,resp:"Integrador",
   q:"¿Pinzas diseñadas para no soltar carga ante pérdida de energía?",
   e:"Válvulas de retención o diseño mecánico pasivo.",
  },
  {id:"r76",code:"6.6",num:76,phase:6,section:"D. Prevención de atrapamientos",optional:true,resp:"Integrador",
   q:"¿Holgura mínima de 500mm respecto a estructuras fijas?",
   e:"Evitar aplastamiento de cuerpo entero.",
  },
  {id:"r77",code:"6.7",num:77,phase:6,section:"D. Prevención de atrapamientos",optional:true,resp:"Integrador",
   q:"¿Medios para rescate de personal atrapado (frenos manuales)?",
   e:"Procedimiento visible en la celda.",
  },

  // ═══════════════════════════════════════════════════════════════
  // FASE 7 — Legislación (4 ítems)
  // ═══════════════════════════════════════════════════════════════
  {id:"r78",code:"7.1",num:78,phase:7,section:"Legislación",optional:false,resp:"Fabricante",
   q:"¿Cumple con Decreto 351/79 (Capítulo 19)?",
   e:"Reglamentación de higiene y seguridad en Argentina.",
  },
  {id:"r79",code:"7.2",num:79,phase:7,section:"Legislación",optional:false,resp:"Usuario",
   q:"¿Identificadas obligaciones del empleador s/ Ley 19587?",
   e:"Capacitación y registros de mantenimiento.",
  },
  {id:"r80",code:"7.3",num:80,phase:7,section:"Legislación",optional:false,resp:"Integrador",
   q:"¿Verificación s/ NR-12 (Brasil) si aplica?",
   e:"Punto de referencia internacional de rigor.",
  },
  {id:"r81",code:"7.4",num:81,phase:7,section:"Legislación",optional:false,resp:"Evaluador",
   q:"¿Prevista evaluación de riesgos adicionales (ruido, calor)?",
   e:"Res. SRT 85/2012 y metodologías específicas.",
  },
];


export const NR12 = [
  { id: "c01", num: 1, cat: "Infraestructura", desc: "Áreas de circulación debidamente demarcadas" },
  { id: "c02", num: 2, cat: "Infraestructura", desc: "Áreas de circulación mantenidas sin obstrucciones" },
  { id: "c03", num: 3, cat: "Infraestructura", desc: "Pisos adecuados (resistentes, sin riesgos adicionales)" },
  { id: "c04", num: 4, cat: "Organización", desc: "Herramientas organizadas en lugares específicos" },
  { id: "c05", num: 5, cat: "Procedimientos", desc: "Procedimiento para movimiento aéreo de materiales" },
  { id: "c06", num: 6, cat: "Documentación", desc: "Diagramas eléctricos completos" },
  { id: "c07", num: 7, cat: "Documentación", desc: "Diagramas neumáticos completos" },
  { id: "c08", num: 8, cat: "Evaluación adicional", desc: "Sustancias peligrosas" },
  { id: "c09", num: 9, cat: "Evaluación adicional", desc: "Radiaciones" },
  { id: "c10", num: 10, cat: "Evaluación adicional", desc: "Vibraciones" },
  { id: "c11", num: 11, cat: "Evaluación adicional", desc: "Ruido" },
  { id: "c12", num: 12, cat: "Evaluación adicional", desc: "Calor" },
  { id: "c13", num: 13, cat: "Mantenimiento", desc: "Registro de mantenimiento preventivo" },
  { id: "c14", num: 14, cat: "Procedimientos", desc: "LOTO - Bloqueo de energías" },
  { id: "c15", num: 15, cat: "Documentación", desc: "Placa de identificación" },
  { id: "c16", num: 16, cat: "Documentación", desc: "Manual de instrucciones" },
  { id: "c17", num: 17, cat: "Procedimientos", desc: "Procedimiento de trabajo" },
  { id: "c18", num: 18, cat: "Mantenimiento", desc: "Registro de inspección de rutina" },
  { id: "c19", num: 19, cat: "RRHH", desc: "Capacitación de trabajadores (EPI)" },
  { id: "c20", num: 20, cat: "RRHH", desc: "Registro de suministros de EPP" },
  { id: "c21", num: 21, cat: "Eléctrico", desc: "Sistema de puesta a tierra" },
  { id: "c22", num: 22, cat: "Ergonomía", desc: "Análisis ergonómico" },
  { id: "c23", num: 23, cat: "Ambiente", desc: "Niveles de iluminación" },
  { id: "c24", num: 24, cat: "Procedimientos", desc: "Trabajo en altura" },
  { id: "c25", num: 25, cat: "Procedimientos", desc: "Espacio confinado" },
];

export const NORMS = {
  A: [
    { code: "ISO 12100:2010", desc: "Principios generales de diseño — Seguridad de máquinas" },
    { code: "ISO/TR 14121-2", desc: "Guía práctica para reducción del riesgo" },
  ],
  B: [
    { code: "ISO 13849-1", desc: "Partes de sistemas de mando — Niveles de rendimiento (PL)" },
    { code: "ISO 13849-2", desc: "Partes de sistemas de mando — Validación" },
    { code: "ISO 13855", desc: "Posicionamiento de protectores — velocidad de aproximación" },
    { code: "ISO 13857", desc: "Distancias de seguridad — zonas peligrosas" },
  ],
  C: [
    { code: "ISO 10218-1", desc: "Robots industriales — Diseño (fabricante)" },
    { code: "ISO 10218-2", desc: "Robots industriales — Integración de sistemas" },
  ],
  Local: [
    { code: "Ley 19587", desc: "Higiene y Seguridad en el Trabajo — Argentina" },
    { code: "Decreto 351/79", desc: "Reglamento de Higiene y Seguridad — Argentina" },
    { code: "NR-12", desc: "Segurança no trabalho em máquinas e equipamentos — Brasil" },
  ],
};
